name: Build iOS App

on:
  workflow_dispatch:
    inputs:
      godot_version:
        description: 'Godot Version (z.B. 4.3)'
        required: true
        default: '4.3'
      export_preset:
        description: 'Name deines Export-Presets in Godot'
        required: true
        default: 'iOS'

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Download and Setup Godot Engine
        run: |
          curl -LO "https://github.com{{ github.event.inputs.godot_version }}-stable/Godot_v${{ github.event.inputs.godot_version }}-stable_macos.universal.zip"
          unzip -q Godot_v${{ github.event.inputs.godot_version }}-stable_macos.universal.zip
          mv Godot.app /Applications/Godot.app

      - name: Export Godot Project to Xcode
        run: |
          mkdir -p build/ios
          /Applications/Godot.app/Contents/MacOS/Godot --headless --export-release "${{ github.event.inputs.export_preset }}" build/ios/JumpingKnight.ipa

      - name: Upload Unsigned IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-build
          path: build/ios/



