name: Build iOS
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Godot 4.3
        run: |
          mkdir -p build/ios
          wget https://github.com
          unzip Godot_v4.3-stable_linux.x86_64.zip
          mv Godot_v4.3-stable_linux.x86_64 godot
          
      - name: Export Project to IPA
        run: |
          ./godot --headless --export-release "iOS" build/ios/JumpingKnight.ipa
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/

