name: Build iOS
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Godot 4.3
        uses: amir-s/setup-godot@v1
        with:
          version: '4.3'
          
      - name: Export Project to IPA
        run: |
          mkdir -p build/ios
          godot --headless --export-release "iOS" build/ios/JumpingKnight.ipa
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/

